### ISSUE TITLE
[NR3 2.2] Long Station Names with Statuses

### ISSUE THREAD

**Issue by test137E29B** [jfoot/Bus-Departure-Board#11]
**Describe the bug**
Long station names such as "Aylesbury Vale Parkway" can interfere with status such as "Cancelled" and "On Time" as the text is right up against "On Time" and "Cancelled" is layered on top.  Potentially station name should be less wide, and scroll?

**To Reproduce**
Steps to reproduce the behaviour:
1. Run NationalRail3 v2.2, with station code AYS

**Expected behaviour**
There should be some gap between station name for the train destination, and the status of the train, and should not get overlayed with other longer statuses such as Cancellled

**Screenshots or Error Trace**
Appears as "Aylesbury Vale ParkwaOn time" on the display

**Program information:**
 - Pi Type [e.g. Pi Zero WH]
 - Program [e.g. NationalRail3.py]
 - Version [e.g. 2.2NR]

**Additional context**
This only seems to be an issue with longer station names of course.

**Comment by jfoot** [comment]
Hi there, thanks for the bug report, I think I'll implement dynamic font-size scaling to shrink down the size of the platform name and make it fit. Too many animations causes the Pi Zero to struggle and slows down a fair bit. I've now labelled it as work-planed as I'm a rather busy currently. But I should have this fixed around mid-May. Thanks again.

**Comment by jfoot** [comment]
Hi again @test137E29B , really sorry this took much longer than originally planned, uni exams, dissertation and house moving all got in the way and then implementing dynamically scaling proved to be harder than originally anticipated . I really really need to refactor my code base, getting a bit spegethii now. 

Anyhow, this should now have been resolved and a fix has been pushed to the dev branch, it will be pushed out to the master branch tonight or tommrow and your display should auto-update to V2.3.NR within 3 days. Or alternatively you can always do "git pull" to force it to do it now once the master has been merged too.  Please let me know if your still experiencing any problems with this after receiving the update :) 

![image](https://user-images.githubusercontent.com/27645114/126040793-8ab5f0a5-a56f-43b1-9067-21a3ff982391.png)
