### ISSUE TITLE
NationalBusesPy3.py & LondonUndergroundPy3.py

### ISSUE THREAD

**Issue by iainwobs** [jfoot/Bus-Departure-Board#28]
**Describe the bug**

Steps to reproduce the behaviour
raspberrybus:~ $ sudo python3 ~/Bus-Departure-Board/LondonUndergroundPy3.py -k xxxxxxxxxxxxxxxxxxxxxxxxx -s 940GZZLULNB -x Jubilee -p 'both'
Traceback (most recent call last):
  File "/home/pi/Bus-Departure-Board/LondonUndergroundPy3.py", line 79, in <module>
    BasicFont = ImageFont.truetype("%s/resources/lower.ttf" %(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))) ),14)
AttributeError: module 'PIL.ImageFont' has no attribute 'truetype'
pi@raspberrybus:~ $ sudo python3 ~/Bus-Departure-Board/NationalBusesPy3.py -k xxxxxxxxxxxxxxxxxxxxxxxxx -a yyyyyyy -s 1500IM451B -b no -y 0 -o 1 -e dim -i 23:59-09:00 -l 120 -v 8
Traceback (most recent call last):
  File "/home/pi/Bus-Departure-Board/NationalBusesPy3.py", line 85, in <module>
    BasicFont = ImageFont.truetype("%s/resources/lower.ttf" % (os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))),14)
AttributeError: module 'PIL.ImageFont' has no attribute 'truetype'

the display worked great a few days ago but I now getting the above error message/s. Looks like a missing or removed font.

iain

**Comment by jfoot** [comment]
Hi @iainwobs, I've not been able to reproduce this error currently. Please can we first check you do have the font files and they've not somehow disappeared. Please SSH into your pi, then type the following commands:

1. `cd /home/pi/Bus-Departure-Board/resources/`
2. `ls`


You should then see the following files:
![image](https://user-images.githubusercontent.com/27645114/153719803-c4d5610e-000c-4ac2-8bc8-3a1d7ed5f5f7.png)


If you do have all these files, please can you try and edit the national buses code line 85 and line 86 to the following:

```
## Defines all the programs "global" variables 
# Defines the fonts used throughout most the program
BasicFont = ImageFont.truetype("/home/pi/Bus-Departure-Board/resources/lower.ttf",14)
SmallFont = ImageFont.truetype("/home/pi/Bus-Departure-Board/resources/lower.ttf",12)
```

Then in the London Underground program please edit line 79 to the following:

```
## Defines all the programs "global" variables 
# Defines the basic font used throughout most of the text boxes in the program
BasicFont = ImageFont.truetype("/home/pi/Bus-Departure-Board/resources/lower.ttf",14)
```

If it still fails then I'm a little bit lost with this one... It might be easiest to completely re-flash your pi and start from scratch. Depending on the age of your pi/ when you flashed your SD card, you might have a rather old version of Raspbian OS. A fresh install would get the latest version and help rule out any issues. Although, I can appreciate this would take a little bit of time :(  Make sure to backup your **startupDisplay.sh** file to easily regain your API keys and program settings.

**Comment by iainwobs** [comment]
thanks again
