### ISSUE TITLE
LondonUndergroundPy3.py fatal crash overnight due to item not in list.

### ISSUE THREAD

**Issue by technoweenie1** [jfoot/Bus-Departure-Board#36]
**Describe the bug**
The program will completely crash and the display screen shows blank. The error logs are attached below.

**To Reproduce**
1. Program set for default inactive hours.
2. London TfL stop ID -s 490012211N --FixNextToArrive --no-console-output
3. Next morning the screen is blank and the program has fatal error listed below.

**Expected behaviour**
Continues to operate waking next morning after inactive hours.

**Screenshots or Error Trace**
![py error](https://github.com/jfoot/Bus-Departure-Board/assets/44537711/5a415119-93ca-4a03-8c18-a8baa5fbe341)

**Program information:**
 - Pi Type: Pi 4 Model B
 - Program: LondonUndergroundPy3.py.py
 - Stop/Station ID: 490012211N
 - Program Args: --FixNextToArrive --no-console-output
 - Version: 2.5.LU

**Additional context**
Raspberry Pi OS (Legacy) Lite
    Release date: December 5th 2023
    System: 32-bit
    Kernel version: 6.1
    Debian version: 11 (bullseye)
Python ver 3.9.2

I think this may be the same problem as issue #2 

Cheers,
          Bryan.

**Comment by jfoot** [comment]
Hey @technoweenie1, thanks for the report, I've been a little busy recently, but will try and take a look at this when I can.

**Comment by technoweenie1** [comment]
Tried a new install on a Pi2w with latest Git pull, and I am getting the same crash overnight. Any thoughts on this?

**Comment by jfoot** [comment]
Hey @technoweenie1, sorry about taking such a long time to look into this. I've tentativly fixed this for you, you'll need to pull in the latest changes, run:  `git -C ./Bus-Departure-Board/ pull` Hopefully that works, if not let me know and I'll take a proper look into this early next month.

**Comment by technoweenie1** [comment]
Sign has been working flawlessly. Many thanks.
