### ISSUE TITLE
Blank screen - No data

### ISSUE THREAD

**Issue by gui1207** [jfoot/Bus-Departure-Board#40]
**Describe the bug**
I have installed all the dependencies and the example and run the DemoPy3, and it's working fine. The screen turns on, and I can see data.
While trying to test with NationalRailPy3 or LondonUndergroundPy3 the script initializes, I don't see any errors in the console but the screen doesn't show any data. It initializes with the splash screen but then doesn't show any data.
I have tried inserting an invalid credential, and then I can see some errors in the log. 
I have tested the credentials with Postman, and they are working and returning data. 

Would you happen to know anything I can try to debug?

**Comment by jfoot** [comment]
Hey @gui1207, I think whats happening is you're setting up your display late at night? If so, it will turn off the screen by default 23:00-07:00 to prevent screen burn in. If you want to alter the time of day your display turns off for add the following argument "-i" followed by the start and end time, for example "-i 23:30-03:00" would turn off between 23:30 and 3am the next day. If it's still not working let me know. :)

**Comment by gui1207** [comment]
Hey @jfoot. Lol, that was the issue :) 

Thanks mate!
